# Generated by Django 5.2.11 on 2026-05-23 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_admin', '0001_initial'),
        ('My_app', '0002_login_age_login_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprogress',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='My_admin.sqlquestion'),
        ),
        migrations.AddField(
            model_name='login',
            name='sql_academy_level',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='SQLQuestion',
        ),
    ]
