# Generated by Django 5.2.11 on 2026-06-12 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_app', '0003_alter_userprogress_question_login_sql_academy_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='assessment_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='login',
            name='assessment_level',
            field=models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('expert', 'Expert')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='login',
            name='assessment_score',
            field=models.IntegerField(default=0),
        ),
    ]
