# Generated by Django 5.2.11 on 2026-05-23 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name='SQLQuestion',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('question', models.TextField()),
                        ('methods', models.TextField()),
                        ('difficulty', models.CharField(max_length=10)),
                        ('model_no', models.IntegerField()),
                        ('answer', models.TextField()),
                        ('option', models.TextField()),
                        ('sample_data', models.JSONField()),
                    ],
                    options={
                        'db_table': 'My_app_sqlquestion',
                    },
                ),
            ]
        )
    ]
