# Generated by Django 5.2.11 on 2026-06-03 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SqlDictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=200)),
                ('meaning', models.TextField()),
                ('analogy', models.TextField(blank=True, default='')),
                ('syntax', models.TextField(blank=True, default='')),
                ('example_query', models.TextField(blank=True, default='')),
                ('icon', models.CharField(blank=True, default='BookOpen', max_length=100)),
                ('color', models.CharField(blank=True, default='from-blue-400 to-indigo-600', max_length=200)),
                ('questions', models.JSONField(blank=True, default=list)),
            ],
            options={
                'db_table': 'My_admin_sqldictionary',
                'ordering': ['id'],
            },
        ),
    ]
