# Generated by Django 5.2.11 on 2026-06-03 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_admin', '0002_sqldictionary'),
    ]

    operations = [
        migrations.CreateModel(
            name='SqlAcademy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('instruction', models.TextField()),
                ('expectedQuery', models.TextField()),
                ('columns', models.JSONField(blank=True, default=list)),
                ('tableData', models.JSONField(blank=True, default=list)),
                ('successMsg', models.TextField()),
                ('hint', models.TextField()),
            ],
            options={
                'db_table': 'My_admin_sqlacademy',
                'ordering': ['id'],
            },
        ),
    ]
